[network]
name = "Development"
subnet = "10.0.0.0/8"

[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "test test test test test test test test test test test junk"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong"
balance = 1_000_000_000_000

[devnet]
# Settings for the Clarinet Devnet
